apiVersion : apps/v1
kind: Deployment
metadata:
  name: "ubulog-web"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "ubulog-web"
  template:
    metadata:
      labels:
        app: "ubulog-web"
    spec:
      containers:
        - name: "ubulog-web"
          image: "ubuntuchatlog.azurecr.io/ubulog-web"
          ports:
          - containerPort: 3000