apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ubulog-web
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: ubulog.com
      http:
        paths:
          - backend:
              service:
                name:  ubulog-web
                port:
                  number: 80
