apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatlog-web
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager/issuer: letsencrypt
spec:
  rules:
    - host: ubulog.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chatlog-web
                port:
                  number: 3000
  tls:
    - hosts:
        - ubulog.com
      secretName: ubulog-web-tls
