name: 🚀 Deploy to Production

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - uses: actions/checkout@master
    
    # - uses: azure/docker-login@v1
    #   with:
    #     login-server: ubuntuchatlog.azurecr.io
    #     username: ${{ secrets.acr_ubuntuchatlog_username }}
    #     password: ${{ secrets.acr_ubuntuchatlog_password }}
    
    # - name: Build and push image to ACR
    #   id: build-image
    #   run: |
    #     docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t ubuntuchatlog.azurecr.io/ubuntu-chatlog-web:${{ github.sha }} --label dockerfile-path=Dockerfile
    #     docker push ubuntuchatlog.azurecr.io/ubuntu-chatlog-web:${{ github.sha }}
    
    # - uses: azure/k8s-set-context@v1
    #   with:
    #      kubeconfig: ${{ secrets.aks_danik8s_kubeConfig }}
    #   id: login

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to Docker Hub
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          diddledan/ubuntu-chatlog-web:${{ github.sha }}
          diddledan/ubuntu-chatlog-web:latest
    
    # - name: Create namespace
    #   run: |
    #     namespacePresent=`kubectl get namespace | grep ubuntu-chatlogs | wc -l`
    #     if [ $namespacePresent -eq 0 ]
    #     then
    #         echo `kubectl create namespace ubuntu-chatlogs`
    #     fi

    # - uses: azure/k8s-create-secret@v1
    #   with:
    #     namespace: ubuntu-chatlogs
    #     container-registry-url: ubuntuchatlog.azurecr.io
    #     container-registry-username: ${{ secrets.acr_ubuntuchatlog_username }}
    #     container-registry-password: ${{ secrets.acr_ubuntuchatlog_password }}
    #     secret-name: danik8sdockerauth

    # - uses: azure/k8s-deploy@v1.2
    #   with:
    #     namespace: ubuntu-chatlogs
    #     manifests: |
    #       manifests/deployment.yml
    #       manifests/service.yml
    #       manifests/ingress.yml
    #     images: |
    #       ubuntuchatlog.azurecr.io/ubuntu-chatlog-web:${{ github.sha }}
    #     imagepullsecrets: |
    #       danik8sdockerauth
